"""initial warehouse schema

Revision ID: 6b003a86a122
Revises: 
Create Date: 2026-06-02 21:27:52.179195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b003a86a122'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('folder_name', sa.String(length=100), nullable=True),
    sa.Column('gmail_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_filter', sa.Boolean(), nullable=False),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_clients_customer_email'), 'email_clients', ['customer_email'], unique=True)
    op.create_index(op.f('ix_email_clients_customer_name'), 'email_clients', ['customer_name'], unique=False)
    op.create_index(op.f('ix_email_clients_id'), 'email_clients', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('salary_base', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_driver', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'PICKER', 'DRIVER', 'OFFICE', name='employeerole'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_dni'), 'employees', ['dni'], unique=True)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('aisle', sa.String(length=10), nullable=False),
    sa.Column('rack', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('current_load', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_aisle'), 'locations', ['aisle'], unique=False)
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('niu', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.Enum('KG', 'UNIT', 'BOX', 'PALLET', name='unittype'), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('price_cost', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_niu'), 'products', ['niu'], unique=True)
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='emailpriority'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('folder_assigned', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('office_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('office_notified_to', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['email_clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_from_email'), 'email_messages', ['from_email'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_message_id'), 'email_messages', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_index(op.f('ix_email_messages_received_at'), 'email_messages', ['received_at'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('ENTRY', 'EXIT', 'REPLENISHMENT', 'RETURN', 'ADJUSTMENT', name='movementtype'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_date'), 'movements', ['date'], unique=False)
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.create_index(op.f('ix_movements_reference'), 'movements', ['reference'], unique=False)
    op.create_index(op.f('ix_movements_type'), 'movements', ['type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKING', 'COMPLETED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('conformity_signed', sa.Boolean(), nullable=False),
    sa.Column('conformity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conformity_notes', sa.Text(), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('salary_base', sa.Float(), nullable=False),
    sa.Column('bonuses', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='payrollstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_payroll_employee_period')
    )
    op.create_index(op.f('ix_payrolls_employee_id'), 'payrolls', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrolls_id'), 'payrolls', ['id'], unique=False)
    op.create_table('product_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_product_location')
    )
    op.create_index(op.f('ix_product_locations_id'), 'product_locations', ['id'], unique=False)
    op.create_index(op.f('ix_product_locations_location_id'), 'product_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_product_locations_product_id'), 'product_locations', ['product_id'], unique=False)
    op.create_table('replenishments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='replenishmentstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='replenishmentpriority'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishments_created_at'), 'replenishments', ['created_at'], unique=False)
    op.create_index(op.f('ix_replenishments_id'), 'replenishments', ['id'], unique=False)
    op.create_index(op.f('ix_replenishments_status'), 'replenishments', ['status'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('capacity_m3', sa.Float(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_id'), 'trucks', ['id'], unique=False)
    op.create_index(op.f('ix_trucks_plate'), 'trucks', ['plate'], unique=True)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('type', sa.Enum('TRUCK', 'PAYROLL', 'MEETING', 'DELIVERY', 'OTHER', name='calendareventtype'), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_date'), 'calendar_events', ['date'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_table('movement_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_lines_id'), 'movement_lines', ['id'], unique=False)
    op.create_index(op.f('ix_movement_lines_movement_id'), 'movement_lines', ['movement_id'], unique=False)
    op.create_index(op.f('ix_movement_lines_product_id'), 'movement_lines', ['product_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Float(), nullable=False),
    sa.Column('quantity_picked', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKED', 'MISSING', 'PARTIAL', name='orderlinestatus'), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('picked_by', sa.Integer(), nullable=True),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picked_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_id'), 'order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_product_id'), 'order_lines', ['product_id'], unique=False)
    op.create_table('replenishment_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('replenishment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('current_qty', sa.Float(), nullable=False),
    sa.Column('min_qty', sa.Float(), nullable=False),
    sa.Column('requested_qty', sa.Float(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replenishment_id'], ['replenishments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_lines_id'), 'replenishment_lines', ['id'], unique=False)
    op.create_index(op.f('ix_replenishment_lines_product_id'), 'replenishment_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_replenishment_lines_replenishment_id'), 'replenishment_lines', ['replenishment_id'], unique=False)
    op.create_table('truck_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schedule_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='scheduletype'), nullable=False),
    sa.Column('route_description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_ROUTE', 'COMPLETED', 'CANCELLED', name='schedulestatus'), nullable=False),
    sa.Column('orders_assigned', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_schedules_date'), 'truck_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_truck_schedules_id'), 'truck_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_truck_schedules_status'), 'truck_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_truck_schedules_truck_id'), 'truck_schedules', ['truck_id'], unique=False)
    op.create_table('truck_returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('truck_schedule_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['truck_schedule_id'], ['truck_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_returns_id'), 'truck_returns', ['id'], unique=False)
    op.create_index(op.f('ix_truck_returns_order_id'), 'truck_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_truck_returns_product_id'), 'truck_returns', ['product_id'], unique=False)
    op.create_index(op.f('ix_truck_returns_truck_schedule_id'), 'truck_returns', ['truck_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_returns_truck_schedule_id'), table_name='truck_returns')
    op.drop_index(op.f('ix_truck_returns_product_id'), table_name='truck_returns')
    op.drop_index(op.f('ix_truck_returns_order_id'), table_name='truck_returns')
    op.drop_index(op.f('ix_truck_returns_id'), table_name='truck_returns')
    op.drop_table('truck_returns')
    op.drop_index(op.f('ix_truck_schedules_truck_id'), table_name='truck_schedules')
    op.drop_index(op.f('ix_truck_schedules_status'), table_name='truck_schedules')
    op.drop_index(op.f('ix_truck_schedules_id'), table_name='truck_schedules')
    op.drop_index(op.f('ix_truck_schedules_date'), table_name='truck_schedules')
    op.drop_table('truck_schedules')
    op.drop_index(op.f('ix_replenishment_lines_replenishment_id'), table_name='replenishment_lines')
    op.drop_index(op.f('ix_replenishment_lines_product_id'), table_name='replenishment_lines')
    op.drop_index(op.f('ix_replenishment_lines_id'), table_name='replenishment_lines')
    op.drop_table('replenishment_lines')
    op.drop_index(op.f('ix_order_lines_product_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_movement_lines_product_id'), table_name='movement_lines')
    op.drop_index(op.f('ix_movement_lines_movement_id'), table_name='movement_lines')
    op.drop_index(op.f('ix_movement_lines_id'), table_name='movement_lines')
    op.drop_table('movement_lines')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_date'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_trucks_plate'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_id'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_replenishments_status'), table_name='replenishments')
    op.drop_index(op.f('ix_replenishments_id'), table_name='replenishments')
    op.drop_index(op.f('ix_replenishments_created_at'), table_name='replenishments')
    op.drop_table('replenishments')
    op.drop_index(op.f('ix_product_locations_product_id'), table_name='product_locations')
    op.drop_index(op.f('ix_product_locations_location_id'), table_name='product_locations')
    op.drop_index(op.f('ix_product_locations_id'), table_name='product_locations')
    op.drop_table('product_locations')
    op.drop_index(op.f('ix_payrolls_id'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_employee_id'), table_name='payrolls')
    op.drop_table('payrolls')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_movements_type'), table_name='movements')
    op.drop_index(op.f('ix_movements_reference'), table_name='movements')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_date'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_email_messages_received_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_gmail_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_from_email'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_products_niu'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_index(op.f('ix_locations_aisle'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_dni'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_email_clients_id'), table_name='email_clients')
    op.drop_index(op.f('ix_email_clients_customer_name'), table_name='email_clients')
    op.drop_index(op.f('ix_email_clients_customer_email'), table_name='email_clients')
    op.drop_table('email_clients')
    # ### end Alembic commands ###
